export type PortfolioItemType =
  | 'Software'
  | 'Research'
  | 'Design'
  | 'Writing'
  | 'Business'
  | 'Engineering'
  | 'Art'
  | 'Health'
  | 'Education'
  | 'Community';

type Format = 'Paper' | 'Poster' | 'Deck' | 'Video' | 'Prototype' | 'Gallery' | 'Code' | 'Report';

type DetailTemplate = 'CaseStudy' | 'Research' | 'Creative';

type LinkItem = { label: string; url: string };

export type PortfolioItem = {
  id: string;
  studentId: string;
  type: PortfolioItemType;
  title: string;
  summary: string;
  tags: string[];
  updatedAt: string;
  heroImageUrl: string;
  format: Format;
  detailTemplate: DetailTemplate;
  links: LinkItem[];
};

export type Skill = { category: string; name: string; level: 'Beginner' | 'Intermediate' | 'Advanced' };

export type Student = {
  id: string;
  name: string;
  headline: string;
  bio: string;
  year: number;
  location: string;
  avatarUrl: string;
  links: { github?: string; linkedin?: string; website?: string; portfolio?: string; email?: string };
  strengths: string[];
  fields: string[];
  interests: string[];
  skills: Skill[];
  portfolioItems: PortfolioItem[];
  featuredItemId: string;
};

export type Opportunity = {
  id: string;
  title: string;
  org: string;
  category: PortfolioItemType;
  summary: string;
  fields: string[];
  tags: string[];
  formatDesired: string[];
  updatedAt: string;
};

const avatar = (seed: string) => `https://api.dicebear.com/7.x/thumbs/svg?seed=${seed}`;
const hero = (seed: string) => `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=1200&q=80`;

const portfolioItems: PortfolioItem[] = [
  {
    id: 'pi1',
    studentId: 's1',
    type: 'Research',
    title: 'Accessibility on Campus',
    summary: 'Mixed-methods study on accessible navigation for students with mobility needs.',
    tags: ['Accessibility', 'Survey', 'Interviews'],
    updatedAt: '3d ago',
    heroImageUrl: hero('photo-1503676260728-1c00da094a0b'),
    format: 'Report',
    detailTemplate: 'Research',
    links: [{ label: 'Read report', url: 'https://example.com/report' }],
  },
  {
    id: 'pi2',
    studentId: 's1',
    type: 'Design',
    title: 'Wayfinding System',
    summary: 'Visual system for campus signage with clear hierarchy and pictograms.',
    tags: ['Visual design', 'Signage'],
    updatedAt: '1w ago',
    heroImageUrl: hero('photo-1460925895917-afdab827c52f'),
    format: 'Poster',
    detailTemplate: 'Creative',
    links: [{ label: 'Gallery', url: 'https://example.com/gallery' }],
  },
  {
    id: 'pi3',
    studentId: 's1',
    type: 'Writing',
    title: 'Inclusive Design Playbook',
    summary: 'Guide for student teams to plan inclusive experiences.',
    tags: ['Content', 'Inclusive'],
    updatedAt: '5d ago',
    heroImageUrl: hero('photo-1523475472560-d2df97ec485c'),
    format: 'Report',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Download', url: 'https://example.com/playbook' }],
  },
  {
    id: 'pi4',
    studentId: 's2',
    type: 'Software',
    title: 'Transit Pulse',
    summary: 'Real-time shuttle ETA with rider-friendly UI.',
    tags: ['Transit', 'Mobile'],
    updatedAt: '2d ago',
    heroImageUrl: hero('photo-1553877522-43269d4ea984'),
    format: 'Prototype',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Demo', url: 'https://example.com/demo' }],
  },
  {
    id: 'pi5',
    studentId: 's2',
    type: 'Business',
    title: 'Shuttle Partnerships',
    summary: 'Business model for city-campus transit partnerships.',
    tags: ['Finance', 'Partnerships'],
    updatedAt: '6d ago',
    heroImageUrl: hero('photo-1498050108023-c5249f4df085'),
    format: 'Deck',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Slides', url: 'https://example.com/slides' }],
  },
  {
    id: 'pi6',
    studentId: 's2',
    type: 'Community',
    title: 'Bus Rider Advisory',
    summary: 'Community board to collect rider feedback monthly.',
    tags: ['Community', 'Engagement'],
    updatedAt: '1w ago',
    heroImageUrl: hero('photo-1504384308090-c894fdcc538d'),
    format: 'Report',
    detailTemplate: 'Research',
    links: [{ label: 'Summary', url: 'https://example.com/summary' }],
  },
  {
    id: 'pi7',
    studentId: 's3',
    type: 'Design',
    title: 'Studio North Identity',
    summary: 'Brand kit and microsite for a student creative studio.',
    tags: ['Brand', 'Web'],
    updatedAt: '4d ago',
    heroImageUrl: hero('photo-1523475472560-d2df97ec485c'),
    format: 'Gallery',
    detailTemplate: 'Creative',
    links: [{ label: 'Gallery', url: 'https://example.com/studionorth' }],
  },
  {
    id: 'pi8',
    studentId: 's3',
    type: 'Art',
    title: 'Motion Stings',
    summary: 'Short motion pieces for student org promos.',
    tags: ['Motion', 'Illustration'],
    updatedAt: '1w ago',
    heroImageUrl: hero('photo-1478720568477-152d9b164e26'),
    format: 'Video',
    detailTemplate: 'Creative',
    links: [{ label: 'Reel', url: 'https://example.com/reel' }],
  },
  {
    id: 'pi9',
    studentId: 's3',
    type: 'Writing',
    title: 'Visual Language Guide',
    summary: 'Documentation for consistent visuals across teams.',
    tags: ['Style guide', 'Docs'],
    updatedAt: '2w ago',
    heroImageUrl: hero('photo-1492724441997-5dc865305da7'),
    format: 'Report',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Guide', url: 'https://example.com/guide' }],
  },
  {
    id: 'pi10',
    studentId: 's4',
    type: 'Engineering',
    title: 'Robot Logs Dashboard',
    summary: 'Telemetry dashboard for campus delivery robots.',
    tags: ['Robotics', 'Data'],
    updatedAt: '5d ago',
    heroImageUrl: hero('photo-1505740420928-5e560c06d30e'),
    format: 'Prototype',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Prototype', url: 'https://example.com/robot' }],
  },
  {
    id: 'pi11',
    studentId: 's4',
    type: 'Research',
    title: 'Autonomy Study',
    summary: 'Testing robot navigation on uneven terrain.',
    tags: ['Robotics', 'Field test'],
    updatedAt: '1w ago',
    heroImageUrl: hero('photo-1504384308090-c894fdcc538d'),
    format: 'Report',
    detailTemplate: 'Research',
    links: [{ label: 'Findings', url: 'https://example.com/autonomy' }],
  },
  {
    id: 'pi12',
    studentId: 's4',
    type: 'Writing',
    title: 'Safety Checklist',
    summary: 'Operational checklist for lab robots.',
    tags: ['Safety', 'Ops'],
    updatedAt: '9d ago',
    heroImageUrl: hero('photo-1498050108023-c5249f4df085'),
    format: 'Report',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'PDF', url: 'https://example.com/checklist' }],
  },
  {
    id: 'pi13',
    studentId: 's5',
    type: 'Business',
    title: 'Mentor Marketplace',
    summary: 'Marketplace model to pair freshmen with alumni.',
    tags: ['Marketplace', 'Mentorship'],
    updatedAt: '3d ago',
    heroImageUrl: hero('photo-1551434678-e076c223a692'),
    format: 'Deck',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Slides', url: 'https://example.com/mentor' }],
  },
  {
    id: 'pi14',
    studentId: 's5',
    type: 'Research',
    title: 'Mentorship Impact Study',
    summary: 'Measured outcomes of structured mentorship.',
    tags: ['Impact', 'Survey'],
    updatedAt: '1w ago',
    heroImageUrl: hero('photo-1504384308090-c894fdcc538d'),
    format: 'Report',
    detailTemplate: 'Research',
    links: [{ label: 'Results', url: 'https://example.com/results' }],
  },
  {
    id: 'pi15',
    studentId: 's5',
    type: 'Community',
    title: 'Peer Circles',
    summary: 'Small group sessions for career prep.',
    tags: ['Community', 'Career'],
    updatedAt: '2w ago',
    heroImageUrl: hero('photo-1497366754035-f200968a6e72'),
    format: 'Poster',
    detailTemplate: 'Creative',
    links: [{ label: 'Overview', url: 'https://example.com/circles' }],
  },
  {
    id: 'pi16',
    studentId: 's6',
    type: 'Software',
    title: 'Study Buddy',
    summary: 'Peer matching based on course load and time.',
    tags: ['Matching', 'Mobile'],
    updatedAt: '4d ago',
    heroImageUrl: hero('photo-1553877522-43269d4ea984'),
    format: 'Prototype',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Prototype', url: 'https://example.com/studybuddy' }],
  },
  {
    id: 'pi17',
    studentId: 's6',
    type: 'Education',
    title: 'Intro to Figma Workshop',
    summary: 'Hands-on workshop series for non-design majors.',
    tags: ['Workshop', 'Curriculum'],
    updatedAt: '1w ago',
    heroImageUrl: hero('photo-1523475472560-d2df97ec485c'),
    format: 'Deck',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Slides', url: 'https://example.com/figma' }],
  },
  {
    id: 'pi18',
    studentId: 's6',
    type: 'Writing',
    title: 'Design System Notes',
    summary: 'Notes on building inclusive design systems.',
    tags: ['Systems', 'Accessibility'],
    updatedAt: '9d ago',
    heroImageUrl: hero('photo-1460925895917-afdab827c52f'),
    format: 'Report',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Notes', url: 'https://example.com/notes' }],
  },
  {
    id: 'pi19',
    studentId: 's7',
    type: 'Health',
    title: 'Meal Match',
    summary: 'Meal planning for dietary needs.',
    tags: ['Nutrition', 'Mobile'],
    updatedAt: '3d ago',
    heroImageUrl: hero('photo-1492724441997-5dc865305da7'),
    format: 'Prototype',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Demo', url: 'https://example.com/meal' }],
  },
  {
    id: 'pi20',
    studentId: 's7',
    type: 'Research',
    title: 'Health Equity Study',
    summary: 'Exploring meal access inequities.',
    tags: ['Equity', 'Nutrition'],
    updatedAt: '1w ago',
    heroImageUrl: hero('photo-1483478550801-ceba5fe50e8e'),
    format: 'Report',
    detailTemplate: 'Research',
    links: [{ label: 'Paper', url: 'https://example.com/health' }],
  },
  {
    id: 'pi21',
    studentId: 's7',
    type: 'Writing',
    title: 'Healthy Campus Copy',
    summary: 'Microcopy for wellness nudges.',
    tags: ['Content', 'Wellness'],
    updatedAt: '2w ago',
    heroImageUrl: hero('photo-1504384308090-c894fdcc538d'),
    format: 'Report',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Read', url: 'https://example.com/nudge' }],
  },
  {
    id: 'pi22',
    studentId: 's8',
    type: 'Business',
    title: 'Event Ops',
    summary: 'Operational plan for campus events.',
    tags: ['Ops', 'Planning'],
    updatedAt: '1w ago',
    heroImageUrl: hero('photo-1508780709619-79562169bc64'),
    format: 'Deck',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Deck', url: 'https://example.com/event' }],
  },
  {
    id: 'pi23',
    studentId: 's8',
    type: 'Education',
    title: 'Peer Teaching Kit',
    summary: 'Templates for peer-led workshops.',
    tags: ['Teaching', 'Toolkit'],
    updatedAt: '5d ago',
    heroImageUrl: hero('photo-1478720568477-152d9b164e26'),
    format: 'Deck',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Kit', url: 'https://example.com/kit' }],
  },
  {
    id: 'pi24',
    studentId: 's8',
    type: 'Community',
    title: 'Volunteer Hub',
    summary: 'Connecting students to local causes.',
    tags: ['Volunteer', 'Community'],
    updatedAt: '2w ago',
    heroImageUrl: hero('photo-1492724441997-5dc865305da7'),
    format: 'Prototype',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Prototype', url: 'https://example.com/volunteer' }],
  },
  {
    id: 'pi25',
    studentId: 's9',
    type: 'Art',
    title: 'Gallery Night',
    summary: 'Curated student art show with AR labels.',
    tags: ['Gallery', 'AR'],
    updatedAt: '6d ago',
    heroImageUrl: hero('photo-1504384308090-c894fdcc538d'),
    format: 'Gallery',
    detailTemplate: 'Creative',
    links: [{ label: 'Gallery', url: 'https://example.com/gallery-night' }],
  },
  {
    id: 'pi26',
    studentId: 's9',
    type: 'Design',
    title: 'Poster Series',
    summary: 'Posters highlighting campus clubs.',
    tags: ['Poster', 'Print'],
    updatedAt: '1w ago',
    heroImageUrl: hero('photo-1523475472560-d2df97ec485c'),
    format: 'Poster',
    detailTemplate: 'Creative',
    links: [{ label: 'Posters', url: 'https://example.com/posters' }],
  },
  {
    id: 'pi27',
    studentId: 's9',
    type: 'Writing',
    title: 'Artist Statements',
    summary: 'Statements for collaborating artists.',
    tags: ['Writing', 'Art'],
    updatedAt: '2w ago',
    heroImageUrl: hero('photo-1504384308090-c894fdcc538d'),
    format: 'Report',
    detailTemplate: 'Creative',
    links: [{ label: 'Statements', url: 'https://example.com/statements' }],
  },
  {
    id: 'pi28',
    studentId: 's10',
    type: 'Writing',
    title: 'Content Playbook',
    summary: 'Guidelines for clear student communications.',
    tags: ['Content', 'UX Writing'],
    updatedAt: '3d ago',
    heroImageUrl: hero('photo-1498050108023-c5249f4df085'),
    format: 'Report',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Playbook', url: 'https://example.com/content' }],
  },
  {
    id: 'pi29',
    studentId: 's10',
    type: 'Research',
    title: 'Tone Study',
    summary: 'Research on tone preferences across majors.',
    tags: ['Tone', 'Survey'],
    updatedAt: '1w ago',
    heroImageUrl: hero('photo-1460925895917-afdab827c52f'),
    format: 'Report',
    detailTemplate: 'Research',
    links: [{ label: 'Findings', url: 'https://example.com/tone' }],
  },
  {
    id: 'pi30',
    studentId: 's10',
    type: 'Education',
    title: 'Writing Workshops',
    summary: 'Series on writing for product teams.',
    tags: ['Workshop', 'Writing'],
    updatedAt: '9d ago',
    heroImageUrl: hero('photo-1492724441997-5dc865305da7'),
    format: 'Deck',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Slides', url: 'https://example.com/writing' }],
  },
  {
    id: 'pi31',
    studentId: 's11',
    type: 'Engineering',
    title: 'API Playbook',
    summary: 'API standards for student teams.',
    tags: ['API', 'Docs'],
    updatedAt: '5d ago',
    heroImageUrl: hero('photo-1498050108023-c5249f4df085'),
    format: 'Report',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Docs', url: 'https://example.com/api' }],
  },
  {
    id: 'pi32',
    studentId: 's11',
    type: 'Software',
    title: 'API Explorer',
    summary: 'Tool for exploring campus APIs.',
    tags: ['API', 'Tooling'],
    updatedAt: '1w ago',
    heroImageUrl: hero('photo-1460925895917-afdab827c52f'),
    format: 'Prototype',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Prototype', url: 'https://example.com/explorer' }],
  },
  {
    id: 'pi33',
    studentId: 's11',
    type: 'Business',
    title: 'Service Pricing',
    summary: 'Pricing model for student tech services.',
    tags: ['Pricing', 'Finance'],
    updatedAt: '2w ago',
    heroImageUrl: hero('photo-1483478550801-ceba5fe50e8e'),
    format: 'Deck',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Deck', url: 'https://example.com/pricing' }],
  },
  {
    id: 'pi34',
    studentId: 's12',
    type: 'Design',
    title: 'Transit UI Refresh',
    summary: 'UI update for shuttle app with better contrast.',
    tags: ['UI', 'Accessibility'],
    updatedAt: '4d ago',
    heroImageUrl: hero('photo-1460925895917-afdab827c52f'),
    format: 'Prototype',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Mock', url: 'https://example.com/ui' }],
  },
  {
    id: 'pi35',
    studentId: 's12',
    type: 'Education',
    title: 'Design Crit Kit',
    summary: 'Toolkit for running crits across majors.',
    tags: ['Crit', 'Toolkit'],
    updatedAt: '1w ago',
    heroImageUrl: hero('photo-1523475472560-d2df97ec485c'),
    format: 'Deck',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Kit', url: 'https://example.com/crit' }],
  },
  {
    id: 'pi36',
    studentId: 's12',
    type: 'Writing',
    title: 'Portfolio Templates',
    summary: 'Templates for story-driven case studies.',
    tags: ['Templates', 'Writing'],
    updatedAt: '2w ago',
    heroImageUrl: hero('photo-1498050108023-c5249f4df085'),
    format: 'Report',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Templates', url: 'https://example.com/templates' }],
  },
  {
    id: 'pi37',
    studentId: 's13',
    type: 'Health',
    title: 'Mental Health Zine',
    summary: 'Zine about campus mental health resources.',
    tags: ['Mental health', 'Zine'],
    updatedAt: '6d ago',
    heroImageUrl: hero('photo-1478720568477-152d9b164e26'),
    format: 'Poster',
    detailTemplate: 'Creative',
    links: [{ label: 'PDF', url: 'https://example.com/zine' }],
  },
  {
    id: 'pi38',
    studentId: 's13',
    type: 'Community',
    title: 'Peer Support Network',
    summary: 'Organizing peer listeners for students.',
    tags: ['Support', 'Community'],
    updatedAt: '1w ago',
    heroImageUrl: hero('photo-1483478550801-ceba5fe50e8e'),
    format: 'Report',
    detailTemplate: 'Research',
    links: [{ label: 'Overview', url: 'https://example.com/support' }],
  },
  {
    id: 'pi39',
    studentId: 's13',
    type: 'Education',
    title: 'Resilience Workshop',
    summary: 'Workshop on stress and resilience.',
    tags: ['Workshop', 'Health'],
    updatedAt: '2w ago',
    heroImageUrl: hero('photo-1492724441997-5dc865305da7'),
    format: 'Deck',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Slides', url: 'https://example.com/resilience' }],
  },
  {
    id: 'pi40',
    studentId: 's14',
    type: 'Engineering',
    title: 'Bridge Model',
    summary: 'Scale model testing load and vibration.',
    tags: ['Civil', 'Simulation'],
    updatedAt: '4d ago',
    heroImageUrl: hero('photo-1505740420928-5e560c06d30e'),
    format: 'Report',
    detailTemplate: 'Research',
    links: [{ label: 'Results', url: 'https://example.com/bridge' }],
  },
  {
    id: 'pi41',
    studentId: 's14',
    type: 'Research',
    title: 'Soil Analysis',
    summary: 'Comparing soil samples for structural projects.',
    tags: ['Soil', 'Lab'],
    updatedAt: '1w ago',
    heroImageUrl: hero('photo-1504384308090-c894fdcc538d'),
    format: 'Report',
    detailTemplate: 'Research',
    links: [{ label: 'Paper', url: 'https://example.com/soil' }],
  },
  {
    id: 'pi42',
    studentId: 's14',
    type: 'Business',
    title: 'Infrastructure Pitch',
    summary: 'Pitch deck for smart campus infrastructure.',
    tags: ['Infrastructure', 'Pitch'],
    updatedAt: '2w ago',
    heroImageUrl: hero('photo-1498050108023-c5249f4df085'),
    format: 'Deck',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Deck', url: 'https://example.com/infra' }],
  },
  {
    id: 'pi43',
    studentId: 's15',
    type: 'Art',
    title: 'Campus Murals',
    summary: 'Mural concepts celebrating diversity.',
    tags: ['Mural', 'Art'],
    updatedAt: '3d ago',
    heroImageUrl: hero('photo-1478720568477-152d9b164e26'),
    format: 'Gallery',
    detailTemplate: 'Creative',
    links: [{ label: 'Gallery', url: 'https://example.com/mural' }],
  },
  {
    id: 'pi44',
    studentId: 's15',
    type: 'Writing',
    title: 'Artist Interviews',
    summary: 'Interviews with student artists on process.',
    tags: ['Interviews', 'Art'],
    updatedAt: '1w ago',
    heroImageUrl: hero('photo-1504384308090-c894fdcc538d'),
    format: 'Report',
    detailTemplate: 'Creative',
    links: [{ label: 'Interviews', url: 'https://example.com/interviews' }],
  },
  {
    id: 'pi45',
    studentId: 's15',
    type: 'Community',
    title: 'Art Walk',
    summary: 'Community art walk route and signage.',
    tags: ['Community', 'Art'],
    updatedAt: '2w ago',
    heroImageUrl: hero('photo-1523475472560-d2df97ec485c'),
    format: 'Poster',
    detailTemplate: 'Creative',
    links: [{ label: 'Route', url: 'https://example.com/artwalk' }],
  },
  {
    id: 'pi46',
    studentId: 's16',
    type: 'Education',
    title: 'STEM Outreach',
    summary: 'Workshops for local high school students.',
    tags: ['STEM', 'Outreach'],
    updatedAt: '5d ago',
    heroImageUrl: hero('photo-1508780709619-79562169bc64'),
    format: 'Deck',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Plan', url: 'https://example.com/stem' }],
  },
  {
    id: 'pi47',
    studentId: 's16',
    type: 'Research',
    title: 'Education Impact',
    summary: 'Measuring impact of outreach workshops.',
    tags: ['Impact', 'Education'],
    updatedAt: '1w ago',
    heroImageUrl: hero('photo-1492724441997-5dc865305da7'),
    format: 'Report',
    detailTemplate: 'Research',
    links: [{ label: 'Report', url: 'https://example.com/impact' }],
  },
  {
    id: 'pi48',
    studentId: 's16',
    type: 'Community',
    title: 'Learning Circles',
    summary: 'Community-led learning groups.',
    tags: ['Community', 'Education'],
    updatedAt: '2w ago',
    heroImageUrl: hero('photo-1504384308090-c894fdcc538d'),
    format: 'Report',
    detailTemplate: 'CaseStudy',
    links: [{ label: 'Overview', url: 'https://example.com/circles' }],
  },
];

export const students: Student[] = [
  {
    id: 's1',
    name: 'Imani Cole',
    headline: 'Inclusive design researcher',
    bio: 'Studying accessibility on campus and designing clear wayfinding systems.',
    year: 2025,
    location: 'Baltimore, MD',
    avatarUrl: avatar('Imani'),
    links: {
      github: '',
      linkedin: 'https://linkedin.com/in/imani',
      website: '',
      portfolio: 'https://example.com/cole',
      email: 'imani@example.edu',
    },
    strengths: ['User research', 'Systems thinking', 'Writing'],
    fields: ['Accessibility', 'Urban design'],
    interests: ['Mobility', 'Inclusive tech', 'Student services'],
    skills: [
      { category: 'Research', name: 'Interviews', level: 'Advanced' },
      { category: 'Research', name: 'Surveys', level: 'Intermediate' },
      { category: 'Design', name: 'Figma', level: 'Advanced' },
      { category: 'Writing', name: 'Synthesis', level: 'Advanced' },
    ],
    portfolioItems: portfolioItems.filter((i) => i.studentId === 's1'),
    featuredItemId: 'pi1',
  },
  {
    id: 's2',
    name: 'Noah Bartee',
    headline: 'Product & transit strategy',
    bio: 'Building transit tools and partnership plans for campus mobility.',
    year: 2026,
    location: 'Baltimore, MD',
    avatarUrl: avatar('Noah'),
    links: {
      github: 'https://github.com/noah',
      linkedin: 'https://linkedin.com/in/noah',
      website: '',
      portfolio: 'https://example.com/noah',
      email: 'noah@example.edu',
    },
    strengths: ['Product thinking', 'Systems', 'Facilitation'],
    fields: ['Mobility', 'Public policy'],
    interests: ['Transit equity', 'Data storytelling', 'Community feedback'],
    skills: [
      { category: 'Product', name: 'Roadmapping', level: 'Advanced' },
      { category: 'Engineering', name: 'Prototyping', level: 'Intermediate' },
      { category: 'Business', name: 'Partnerships', level: 'Intermediate' },
    ],
    portfolioItems: portfolioItems.filter((i) => i.studentId === 's2'),
    featuredItemId: 'pi4',
  },
  {
    id: 's3',
    name: 'Serena Liu',
    headline: 'Brand & visual designer',
    bio: 'Creating brand systems and motion for student-led studios.',
    year: 2025,
    location: 'Washington, DC',
    avatarUrl: avatar('Serena'),
    links: { github: '', linkedin: 'https://linkedin.com/in/serena', website: 'https://serenadesign.studio', portfolio: 'https://example.com/serena', email: 'serena@example.edu' },
    strengths: ['Visual design', 'Motion', 'Storytelling'],
    fields: ['Media', 'Arts'],
    interests: ['Identity systems', 'Motion', 'Student studios'],
    skills: [
      { category: 'Design', name: 'Branding', level: 'Advanced' },
      { category: 'Design', name: 'Motion', level: 'Intermediate' },
      { category: 'Writing', name: 'Documentation', level: 'Intermediate' },
    ],
    portfolioItems: portfolioItems.filter((i) => i.studentId === 's3'),
    featuredItemId: 'pi7',
  },
  {
    id: 's4',
    name: 'Malik Green',
    headline: 'Robotics & systems',
    bio: 'Building telemetry and autonomy experiments for campus robots.',
    year: 2027,
    location: 'Baltimore, MD',
    avatarUrl: avatar('Malik'),
    links: { github: 'https://github.com/mgreen', linkedin: '', website: '', portfolio: 'https://example.com/malik', email: 'malik@example.edu' },
    strengths: ['Data analysis', 'Systems', 'Safety'],
    fields: ['Robotics', 'Engineering'],
    interests: ['Automation', 'Data viz', 'Field testing'],
    skills: [
      { category: 'Engineering', name: 'Python', level: 'Intermediate' },
      { category: 'Engineering', name: 'Data viz', level: 'Intermediate' },
      { category: 'Research', name: 'Field studies', level: 'Intermediate' },
    ],
    portfolioItems: portfolioItems.filter((i) => i.studentId === 's4'),
    featuredItemId: 'pi10',
  },
  {
    id: 's5',
    name: 'Zuri Prince',
    headline: 'UX & marketplace strategy',
    bio: 'Designing respectful matching experiences for mentorship and hiring.',
    year: 2026,
    location: 'Baltimore, MD',
    avatarUrl: avatar('Zuri'),
    links: { github: '', linkedin: 'https://linkedin.com/in/zuri', website: '', portfolio: 'https://example.com/zuri', email: 'zuri@example.edu' },
    strengths: ['Content design', 'Strategy', 'Interviews'],
    fields: ['Mentorship', 'Education'],
    interests: ['Career access', 'Marketplace design', 'Community'],
    skills: [
      { category: 'Research', name: 'Interviews', level: 'Advanced' },
      { category: 'Design', name: 'Figma', level: 'Intermediate' },
      { category: 'Business', name: 'Pricing', level: 'Intermediate' },
    ],
    portfolioItems: portfolioItems.filter((i) => i.studentId === 's5'),
    featuredItemId: 'pi13',
  },
  {
    id: 's6',
    name: 'Eli Ramos',
    headline: 'Product ops & frontend',
    bio: 'Rapid prototyping and teaching design tools across majors.',
    year: 2025,
    location: 'Philadelphia, PA',
    avatarUrl: avatar('Eli'),
    links: { github: 'https://github.com/eli', linkedin: 'https://linkedin.com/in/eli', website: '', portfolio: 'https://example.com/eli', email: 'eli@example.edu' },
    strengths: ['Facilitation', 'Rapid prototyping', 'Teaching'],
    fields: ['Education', 'Product'],
    interests: ['Peer learning', 'Design systems', 'Mobile'],
    skills: [
      { category: 'Engineering', name: 'React', level: 'Advanced' },
      { category: 'Design', name: 'Figma', level: 'Advanced' },
      { category: 'Education', name: 'Workshop design', level: 'Intermediate' },
    ],
    portfolioItems: portfolioItems.filter((i) => i.studentId === 's6'),
    featuredItemId: 'pi16',
  },
  {
    id: 's7',
    name: 'Layla Ortiz',
    headline: 'Health equity researcher',
    bio: 'Exploring nutrition, wellness, and equitable access on campus.',
    year: 2024,
    location: 'Baltimore, MD',
    avatarUrl: avatar('Layla'),
    links: { github: '', linkedin: 'https://linkedin.com/in/layla', website: '', portfolio: 'https://example.com/layla', email: 'layla@example.edu' },
    strengths: ['Data analysis', 'Survey design', 'Writing'],
    fields: ['Health', 'Nutrition'],
    interests: ['Food access', 'Behavior change', 'Student wellness'],
    skills: [
      { category: 'Research', name: 'Surveys', level: 'Advanced' },
      { category: 'Research', name: 'Quant analysis', level: 'Intermediate' },
      { category: 'Writing', name: 'Reporting', level: 'Advanced' },
    ],
    portfolioItems: portfolioItems.filter((i) => i.studentId === 's7'),
    featuredItemId: 'pi19',
  },
  {
    id: 's8',
    name: 'Mina Patel',
    headline: 'Operations & education design',
    bio: 'Planning workshops and toolkits that keep teams shipping.',
    year: 2025,
    location: 'Baltimore, MD',
    avatarUrl: avatar('Mina'),
    links: { github: '', linkedin: 'https://linkedin.com/in/mina', website: '', portfolio: 'https://example.com/mina', email: 'mina@example.edu' },
    strengths: ['Planning', 'Writing', 'Facilitation'],
    fields: ['Operations', 'Education'],
    interests: ['Workshops', 'Peer learning', 'Community'],
    skills: [
      { category: 'Business', name: 'Ops planning', level: 'Advanced' },
      { category: 'Education', name: 'Curriculum', level: 'Intermediate' },
      { category: 'Writing', name: 'Documentation', level: 'Advanced' },
    ],
    portfolioItems: portfolioItems.filter((i) => i.studentId === 's8'),
    featuredItemId: 'pi22',
  },
  {
    id: 's9',
    name: 'Andre Fields',
    headline: 'Visual storyteller',
    bio: 'Blending art, AR, and clear storytelling for campus events.',
    year: 2026,
    location: 'Baltimore, MD',
    avatarUrl: avatar('Andre'),
    links: { github: 'https://github.com/andre', linkedin: '', website: '', portfolio: 'https://example.com/andre', email: 'andre@example.edu' },
    strengths: ['Visual design', 'AR concepts', 'Curation'],
    fields: ['Arts', 'Media'],
    interests: ['Exhibitions', 'AR', 'Print'],
    skills: [
      { category: 'Design', name: 'Illustration', level: 'Intermediate' },
      { category: 'Design', name: 'Poster design', level: 'Advanced' },
      { category: 'Writing', name: 'Artist statements', level: 'Intermediate' },
    ],
    portfolioItems: portfolioItems.filter((i) => i.studentId === 's9'),
    featuredItemId: 'pi25',
  },
  {
    id: 's10',
    name: 'Chloe Rivers',
    headline: 'Content & UX writing',
    bio: 'Writing crisp product copy and research summaries.',
    year: 2024,
    location: 'Baltimore, MD',
    avatarUrl: avatar('Chloe'),
    links: { github: '', linkedin: 'https://linkedin.com/in/chloe', website: '', portfolio: 'https://example.com/chloe', email: 'chloe@example.edu' },
    strengths: ['Storytelling', 'Editing', 'Research synthesis'],
    fields: ['Media', 'Product'],
    interests: ['Tone of voice', 'Accessibility', 'Education'],
    skills: [
      { category: 'Writing', name: 'UX writing', level: 'Advanced' },
      { category: 'Writing', name: 'Editing', level: 'Advanced' },
      { category: 'Research', name: 'Surveys', level: 'Intermediate' },
    ],
    portfolioItems: portfolioItems.filter((i) => i.studentId === 's10'),
    featuredItemId: 'pi28',
  },
  {
    id: 's11',
    name: 'Rahul Desai',
    headline: 'Backend & documentation',
    bio: 'Pairing reliable services with clear docs for student teams.',
    year: 2025,
    location: 'Baltimore, MD',
    avatarUrl: avatar('Rahul'),
    links: { github: 'https://github.com/rahul', linkedin: '', website: '', portfolio: 'https://example.com/rahul', email: 'rahul@example.edu' },
    strengths: ['Documentation', 'APIs', 'Planning'],
    fields: ['Engineering', 'Product'],
    interests: ['API design', 'Dev education', 'Reliability'],
    skills: [
      { category: 'Engineering', name: 'Node.js', level: 'Advanced' },
      { category: 'Engineering', name: 'APIs', level: 'Advanced' },
      { category: 'Writing', name: 'Docs', level: 'Advanced' },
    ],
    portfolioItems: portfolioItems.filter((i) => i.studentId === 's11'),
    featuredItemId: 'pi31',
  },
  {
    id: 's12',
    name: 'Jade Collins',
    headline: 'Product designer',
    bio: 'Designing story-led UI for transit and education tools.',
    year: 2025,
    location: 'Baltimore, MD',
    avatarUrl: avatar('Jade'),
    links: { github: '', linkedin: 'https://linkedin.com/in/jade', website: '', portfolio: 'https://example.com/jade', email: 'jade@example.edu' },
    strengths: ['Product design', 'Systems', 'Critique'],
    fields: ['Product', 'Education'],
    interests: ['Accessibility', 'Workshops', 'Transit'],
    skills: [
      { category: 'Design', name: 'UI design', level: 'Advanced' },
      { category: 'Design', name: 'Design systems', level: 'Intermediate' },
      { category: 'Education', name: 'Facilitation', level: 'Intermediate' },
    ],
    portfolioItems: portfolioItems.filter((i) => i.studentId === 's12'),
    featuredItemId: 'pi34',
  },
  {
    id: 's13',
    name: 'Amari West',
    headline: 'Health & community',
    bio: 'Championing peer-led wellness and mental health resources.',
    year: 2024,
    location: 'Baltimore, MD',
    avatarUrl: avatar('Amari'),
    links: { github: '', linkedin: 'https://linkedin.com/in/amari', website: '', portfolio: 'https://example.com/amari', email: 'amari@example.edu' },
    strengths: ['Facilitation', 'Storytelling', 'Community'],
    fields: ['Health', 'Community'],
    interests: ['Mental health', 'Peer support', 'Workshops'],
    skills: [
      { category: 'Community', name: 'Programming', level: 'Advanced' },
      { category: 'Writing', name: 'Storytelling', level: 'Intermediate' },
      { category: 'Education', name: 'Workshop design', level: 'Intermediate' },
    ],
    portfolioItems: portfolioItems.filter((i) => i.studentId === 's13'),
    featuredItemId: 'pi37',
  },
  {
    id: 's14',
    name: 'Priya Nair',
    headline: 'Civil engineering student',
    bio: 'Exploring smart infrastructure and sustainable design.',
    year: 2026,
    location: 'Baltimore, MD',
    avatarUrl: avatar('Priya'),
    links: { github: '', linkedin: 'https://linkedin.com/in/priya', website: '', portfolio: 'https://example.com/priya', email: 'priya@example.edu' },
    strengths: ['Simulation', 'Analysis', 'Presentation'],
    fields: ['Engineering', 'Sustainability'],
    interests: ['Smart cities', 'Public works', 'STEM outreach'],
    skills: [
      { category: 'Engineering', name: 'Modeling', level: 'Intermediate' },
      { category: 'Engineering', name: 'CAD', level: 'Intermediate' },
      { category: 'Writing', name: 'Reporting', level: 'Intermediate' },
    ],
    portfolioItems: portfolioItems.filter((i) => i.studentId === 's14'),
    featuredItemId: 'pi40',
  },
  {
    id: 's15',
    name: 'Lena Brooks',
    headline: 'Artist & curator',
    bio: 'Creating art experiences that invite participation.',
    year: 2025,
    location: 'Baltimore, MD',
    avatarUrl: avatar('Lena'),
    links: { github: '', linkedin: 'https://linkedin.com/in/lena', website: '', portfolio: 'https://example.com/lena', email: 'lena@example.edu' },
    strengths: ['Curation', 'Visual storytelling', 'Community'],
    fields: ['Arts', 'Community'],
    interests: ['Murals', 'Public art', 'Workshops'],
    skills: [
      { category: 'Art', name: 'Painting', level: 'Advanced' },
      { category: 'Design', name: 'Layout', level: 'Intermediate' },
      { category: 'Community', name: 'Event planning', level: 'Intermediate' },
    ],
    portfolioItems: portfolioItems.filter((i) => i.studentId === 's15'),
    featuredItemId: 'pi43',
  },
  {
    id: 's16',
    name: 'Carson Lee',
    headline: 'Education & outreach',
    bio: 'Designing STEM outreach and community learning circles.',
    year: 2025,
    location: 'Baltimore, MD',
    avatarUrl: avatar('Carson'),
    links: { github: '', linkedin: 'https://linkedin.com/in/carson', website: '', portfolio: 'https://example.com/carson', email: 'carson@example.edu' },
    strengths: ['Public speaking', 'Curriculum', 'Facilitation'],
    fields: ['Education', 'Community'],
    interests: ['STEM access', 'Peer learning', 'Workshops'],
    skills: [
      { category: 'Education', name: 'Curriculum', level: 'Advanced' },
      { category: 'Community', name: 'Outreach', level: 'Advanced' },
      { category: 'Writing', name: 'Grants', level: 'Intermediate' },
    ],
    portfolioItems: portfolioItems.filter((i) => i.studentId === 's16'),
    featuredItemId: 'pi46',
  },
];

export const opportunities: Opportunity[] = [
  {
    id: 'o1',
    title: 'Health Equity Fellow',
    org: 'Campus Wellness Lab',
    category: 'Research',
    summary: 'Support a study on nutrition access and student health.',
    fields: ['Health', 'Nutrition'],
    tags: ['Qualitative', 'Quantitative'],
    formatDesired: ['Report', 'Deck'],
    updatedAt: '2d ago',
  },
  {
    id: 'o2',
    title: 'Community Art Lead',
    org: 'Arts Council',
    category: 'Art',
    summary: 'Lead a public art walk with student artists.',
    fields: ['Arts', 'Community'],
    tags: ['Curation', 'Event'],
    formatDesired: ['Gallery', 'Poster'],
    updatedAt: '1w ago',
  },
  {
    id: 'o3',
    title: 'Transit UX Partner',
    org: 'City Mobility Team',
    category: 'Design',
    summary: 'Co-design shuttle interfaces for students and riders.',
    fields: ['Mobility', 'Product'],
    tags: ['Accessibility', 'Product'],
    formatDesired: ['Prototype', 'Deck'],
    updatedAt: '3d ago',
  },
  {
    id: 'o4',
    title: 'STEM Outreach Mentor',
    org: 'Education Outreach',
    category: 'Education',
    summary: 'Host workshops for local high schools.',
    fields: ['Education', 'Community'],
    tags: ['Workshops', 'Mentorship'],
    formatDesired: ['Deck', 'Report'],
    updatedAt: '5d ago',
  },
  {
    id: 'o5',
    title: 'Data Storytelling Intern',
    org: 'Civic Lab',
    category: 'Research',
    summary: 'Turn civic data into clear stories for residents.',
    fields: ['Data', 'Policy'],
    tags: ['Data viz', 'Writing'],
    formatDesired: ['Report', 'Deck'],
    updatedAt: '4d ago',
  },
  {
    id: 'o6',
    title: 'Wellness Writer',
    org: 'Student Wellness',
    category: 'Writing',
    summary: 'Create wellness prompts and microcopy.',
    fields: ['Health', 'Media'],
    tags: ['Content', 'Behavior change'],
    formatDesired: ['Report', 'Poster'],
    updatedAt: '1w ago',
  },
  {
    id: 'o7',
    title: 'Mentorship Program Coordinator',
    org: 'Career Center',
    category: 'Business',
    summary: 'Coordinate mentorship marketplace rollout.',
    fields: ['Education', 'Business'],
    tags: ['Operations', 'Partnerships'],
    formatDesired: ['Deck', 'Report'],
    updatedAt: '6d ago',
  },
  {
    id: 'o8',
    title: 'Campus Stories Videographer',
    org: 'Media Lab',
    category: 'Art',
    summary: 'Film short student stories across majors.',
    fields: ['Media', 'Arts'],
    tags: ['Video', 'Storytelling'],
    formatDesired: ['Video'],
    updatedAt: '3d ago',
  },
  {
    id: 'o9',
    title: 'Sustainability Analyst',
    org: 'Green Office',
    category: 'Engineering',
    summary: 'Analyze campus energy data and propose improvements.',
    fields: ['Sustainability', 'Engineering'],
    tags: ['Energy', 'Data'],
    formatDesired: ['Report', 'Deck'],
    updatedAt: '5d ago',
  },
  {
    id: 'o10',
    title: 'Education Content Designer',
    org: 'Learning Lab',
    category: 'Design',
    summary: 'Design materials for peer-led classes.',
    fields: ['Education', 'Design'],
    tags: ['Curriculum', 'Design'],
    formatDesired: ['Deck', 'Poster'],
    updatedAt: '1w ago',
  },
  {
    id: 'o11',
    title: 'Health Comms Specialist',
    org: 'Health Center',
    category: 'Health',
    summary: 'Craft messaging for health campaigns.',
    fields: ['Health', 'Media'],
    tags: ['Copy', 'Campaign'],
    formatDesired: ['Poster', 'Report'],
    updatedAt: '4d ago',
  },
  {
    id: 'o12',
    title: 'Community Partnership Lead',
    org: 'Neighborhood Alliance',
    category: 'Community',
    summary: 'Build partnerships with local orgs.',
    fields: ['Community', 'Policy'],
    tags: ['Engagement', 'Facilitation'],
    formatDesired: ['Deck', 'Report'],
    updatedAt: '1w ago',
  },
  {
    id: 'o13',
    title: 'Career Sprint Curator',
    org: 'Career Center',
    category: 'Business',
    summary: 'Curate weekly challenges across majors.',
    fields: ['Business', 'Education'],
    tags: ['Programming', 'Content'],
    formatDesired: ['Deck', 'Report'],
    updatedAt: '2d ago',
  },
  {
    id: 'o14',
    title: 'Design System Contributor',
    org: 'Digital Services',
    category: 'Software',
    summary: 'Contribute UI patterns for multi-major apps.',
    fields: ['Product', 'Design'],
    tags: ['Components', 'Accessibility'],
    formatDesired: ['Code', 'Prototype'],
    updatedAt: '3d ago',
  },
  {
    id: 'o15',
    title: 'Research Poster Editor',
    org: 'Research Office',
    category: 'Research',
    summary: 'Help students polish posters for symposium.',
    fields: ['Research', 'Design'],
    tags: ['Poster', 'Editing'],
    formatDesired: ['Poster'],
    updatedAt: '6d ago',
  },
  {
    id: 'o16',
    title: 'Public Speaking Coach',
    org: 'Student Affairs',
    category: 'Education',
    summary: 'Coach students presenting portfolios.',
    fields: ['Education', 'Business'],
    tags: ['Coaching', 'Presentations'],
    formatDesired: ['Deck'],
    updatedAt: '4d ago',
  },
  {
    id: 'o17',
    title: 'Health Tech Evaluator',
    org: 'Health Innovation Lab',
    category: 'Health',
    summary: 'Evaluate student-built health apps.',
    fields: ['Health', 'Product'],
    tags: ['Evaluation', 'UX'],
    formatDesired: ['Report', 'Prototype'],
    updatedAt: '5d ago',
  },
  {
    id: 'o18',
    title: 'Community Data Fellow',
    org: 'Civic Data Hub',
    category: 'Research',
    summary: 'Work with community data sets and share stories.',
    fields: ['Community', 'Data'],
    tags: ['Data viz', 'Storytelling'],
    formatDesired: ['Report', 'Deck'],
    updatedAt: '3d ago',
  },
  {
    id: 'o19',
    title: 'Media Campaign Designer',
    org: 'Communications Office',
    category: 'Design',
    summary: 'Design campaigns for university initiatives.',
    fields: ['Media', 'Arts'],
    tags: ['Campaign', 'Brand'],
    formatDesired: ['Poster', 'Video'],
    updatedAt: '1w ago',
  },
  {
    id: 'o20',
    title: 'Student Journal Editor',
    org: 'Student Journal',
    category: 'Writing',
    summary: 'Edit and curate submissions across majors.',
    fields: ['Media', 'Research'],
    tags: ['Editing', 'Publishing'],
    formatDesired: ['Report', 'Poster'],
    updatedAt: '2w ago',
  },
  {
    id: 'o21',
    title: 'Innovation Challenge Coach',
    org: 'Innovation Hub',
    category: 'Business',
    summary: 'Coach teams entering campus innovation challenges.',
    fields: ['Business', 'Engineering'],
    tags: ['Pitch', 'Coaching'],
    formatDesired: ['Deck'],
    updatedAt: '6d ago',
  },
  {
    id: 'o22',
    title: 'Education Media Producer',
    org: 'Learning Lab',
    category: 'Art',
    summary: 'Produce short videos for course intros.',
    fields: ['Education', 'Media'],
    tags: ['Video', 'Story'],
    formatDesired: ['Video'],
    updatedAt: '5d ago',
  },
  {
    id: 'o23',
    title: 'Wellness Data Assistant',
    org: 'Wellness Analytics',
    category: 'Health',
    summary: 'Analyze anonymized wellness check-ins.',
    fields: ['Health', 'Data'],
    tags: ['Data', 'Reporting'],
    formatDesired: ['Report'],
    updatedAt: '1w ago',
  },
  {
    id: 'o24',
    title: 'Education Research Partner',
    org: 'Teaching Center',
    category: 'Research',
    summary: 'Research active learning pilots.',
    fields: ['Education', 'Research'],
    tags: ['Study', 'Survey'],
    formatDesired: ['Paper', 'Report'],
    updatedAt: '4d ago',
  },
];

export { portfolioItems };
